/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agents;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

public class myDrawPanel extends javax.swing.JPanel {
    BufferedImage image =   new BufferedImage(500, 500, BufferedImage.TYPE_INT_RGB);

    public myDrawPanel() {
        initComponents();

    }
    public void calculateImg(int[][] map,int sizex,int sizey,int coordX,int coordY){
        for (int y = 0; y < sizey; ++y) {
            for (int x = 0; x < sizex; ++x) {
                Color color = Color.GRAY;
                if(map[y][x]==1)
                    color= Color.BLACK;
                else if(map[y][x]==0)
                    color= Color.WHITE;
                else if (map[y][x]>=10)
                    color= Color.GREEN;
                else if(map[y][x]==2)
                    color = Color.RED;
                image.setRGB(x, y, color.getRGB());
            }
        }
        Color color = Color.YELLOW;
        image.setRGB(coordX, coordY, color.getRGB());

    }
    
    public void paint(Graphics g){
        g.drawImage(image, 0, 0,image.getHeight(),image.getWidth(), null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
